services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
  barbar-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3766:3000'
    env_file:
      - .env
    volumes:
      - barbar-logs:/app/winston
      - /app/node_modules
      - .:/app
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  barbar-logs:
